import type { ModuleManifest } from "../../core/types";
import { CashCard, PayableCard, ProfitCard, ReceivableCard } from "./cards";
import { ReportsPage } from "./ReportsPage";

export * from "./calculators";

export const reportsModule: ModuleManifest = {
  key: "reports",
  name: "Financial reports",
  nameAr: "التقارير المالية",
  version: "1.0.0",
  summary:
    "Trial balance, profit & loss, balance sheet, general ledger, aging and cash position — all computed on the device, so they work with no connection.",
  category: "Accounting",
  depends: ["accounting", "documents"],
  sequence: 60,

  setup(ctx) {
    ctx.addRoute({ path: "/reports", element: ReportsPage });
    ctx.addMenu({ path: "/reports", labelKey: "reports.title", icon: "📊", section: "reports", sequence: 10 });

    // Contributed to whichever module renders the dashboard — reports does not import it.
    ctx.addDashboardCard({ id: "reports.profit", sequence: 10, render: ProfitCard });
    ctx.addDashboardCard({ id: "reports.cash", sequence: 20, render: CashCard });
    ctx.addDashboardCard({ id: "reports.receivable", sequence: 30, render: ReceivableCard });
    ctx.addDashboardCard({ id: "reports.payable", sequence: 40, render: PayableCard });

    ctx.addTranslations({
      en: {
        "reports.title": "Reports",
        "reports.subtitle": "Computed from your local ledger — available with no connection.",
        "reports.tab.trial": "Trial balance",
        "reports.tab.pl": "Profit & loss",
        "reports.tab.bs": "Balance sheet",
        "reports.tab.ledger": "General ledger",
        "reports.tab.aging": "Aging",
        "reports.tab.cash": "Cash position",
        "reports.from": "From",
        "reports.to": "To",
        "reports.asOf": "As of",
        "reports.account": "Account",
        "reports.pickAccount": "Choose an account to see its ledger.",
        "reports.empty": "Nothing in this period.",
        "reports.amount": "Amount",
        "reports.total": "Total",
        "reports.balance": "Balance",
        "reports.opening": "Opening balance",
        "reports.closing": "Closing balance",
        "reports.income": "Income",
        "reports.expenses": "Expenses",
        "reports.totalIncome": "Total income",
        "reports.totalExpense": "Total expenses",
        "reports.netProfit": "Net profit",
        "reports.assets": "Assets",
        "reports.liabilities": "Liabilities",
        "reports.equity": "Equity",
        "reports.retained": "Retained earnings",
        "reports.notBalanced": "This report does not balance — that is a bug, not rounding. Please report it.",
        "reports.agingKind": "Side",
        "reports.receivable": "Receivable (customers)",
        "reports.payable": "Payable (suppliers)",
        "reports.daysLate": "Days late",
        "reports.nothingOutstanding": "Nothing outstanding.",
        "reports.bucket.current": "Not due",
        "reports.bucket.d1_30": "1–30 days",
        "reports.bucket.d31_60": "31–60 days",
        "reports.bucket.d61_90": "61–90 days",
        "reports.bucket.d90_plus": "90+ days",
        "reports.inflow": "In",
        "reports.outflow": "Out",
        "dashboard.monthProfit": "Profit this month",
        "dashboard.thisMonth": "From the 1st to today",
        "dashboard.cash": "Cash & bank",
        "dashboard.allCashAccounts": "All cash accounts",
        "dashboard.receivable": "Owed to you",
        "dashboard.payable": "You owe",
        "dashboard.overdue": "{amount}",
      },
      ar: {
        "reports.title": "التقارير",
        "reports.subtitle": "تُحسب من دفاترك المحلية — متاحة بدون اتصال.",
        "reports.tab.trial": "ميزان المراجعة",
        "reports.tab.pl": "قائمة الدخل",
        "reports.tab.bs": "الميزانية العمومية",
        "reports.tab.ledger": "دفتر الأستاذ",
        "reports.tab.aging": "أعمار الديون",
        "reports.tab.cash": "السيولة",
        "reports.from": "من",
        "reports.to": "إلى",
        "reports.asOf": "كما في",
        "reports.account": "الحساب",
        "reports.pickAccount": "اختر حسابًا لعرض كشفه.",
        "reports.empty": "لا توجد حركة في هذه الفترة.",
        "reports.amount": "المبلغ",
        "reports.total": "الإجمالي",
        "reports.balance": "الرصيد",
        "reports.opening": "الرصيد الافتتاحي",
        "reports.closing": "الرصيد الختامي",
        "reports.income": "الإيرادات",
        "reports.expenses": "المصروفات",
        "reports.totalIncome": "إجمالي الإيرادات",
        "reports.totalExpense": "إجمالي المصروفات",
        "reports.netProfit": "صافي الربح",
        "reports.assets": "الأصول",
        "reports.liabilities": "الالتزامات",
        "reports.equity": "حقوق الملكية",
        "reports.retained": "الأرباح المحتجزة",
        "reports.notBalanced": "التقرير غير متوازن — هذا خطأ برمجي وليس تقريبًا. يُرجى الإبلاغ عنه.",
        "reports.agingKind": "الجهة",
        "reports.receivable": "مدينون (عملاء)",
        "reports.payable": "دائنون (موردون)",
        "reports.daysLate": "أيام التأخير",
        "reports.nothingOutstanding": "لا توجد مبالغ مستحقة.",
        "reports.bucket.current": "غير مستحق",
        "reports.bucket.d1_30": "١–٣٠ يومًا",
        "reports.bucket.d31_60": "٣١–٦٠ يومًا",
        "reports.bucket.d61_90": "٦١–٩٠ يومًا",
        "reports.bucket.d90_plus": "أكثر من ٩٠ يومًا",
        "reports.inflow": "وارد",
        "reports.outflow": "صادر",
        "dashboard.monthProfit": "ربح هذا الشهر",
        "dashboard.thisMonth": "من أول الشهر حتى اليوم",
        "dashboard.cash": "النقدية والبنك",
        "dashboard.allCashAccounts": "كل حسابات النقدية",
        "dashboard.receivable": "لك عند الغير",
        "dashboard.payable": "عليك للغير",
        "dashboard.overdue": "{amount}",
      },
    });
  },
};
