"""React escapes everything it renders, except what is handed to
`dangerouslySetInnerHTML`. That one prop is the whole XSS surface of this
frontend, so it is worth pinning: there is exactly one, and it is fed a
server-generated QR SVG, never anything a customer or an employee typed.

A customer's display name, a message body, a knowledge item, a product name --
all of it flows into the inbox and the screens as React children, which React
renders as text. The moment any of it reaches `dangerouslySetInnerHTML`, a
customer who names themselves `<img src=x onerror=...>` runs script in the
owner's session. This file fails if a second sink appears, or if the existing
one starts reading from anything but the QR response.

It is a source sweep, because the property is "the code contains one sink fed
from one place", which is a fact about the files, not about any rendered page.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parent.parent

FRONTEND = ROOT / "frontend" / "src"


def _sinks():
    for path in FRONTEND.rglob("*.jsx"):
        source = path.read_text()

        for match in re.finditer(r"dangerouslySetInnerHTML", source):
            line = source[: match.start()].count("\n") + 1
            yield path, line, source


def test_there_is_exactly_one_raw_html_sink():
    sinks = [(path.relative_to(ROOT), line) for path, line, _ in _sinks()]

    assert len(sinks) == 1, (
        "The number of `dangerouslySetInnerHTML` sinks changed. Each one is an "
        "XSS surface and has to be justified individually:\n  "
        + "\n  ".join(f"{p}:{n}" for p, n in sinks)
    )


def test_the_one_sink_renders_the_server_generated_qr_and_nothing_else():
    path, line, source = next(iter(_sinks()))

    assert path.name == "PlatformEnrolTotpPage.jsx", (
        f"the raw-HTML sink moved to {path.name}; confirm its input is still "
        "server-generated markup, not anything a user typed"
    )

    # The prop is fed `qrSvg`, and `qrSvg` is only ever set from the QR field of
    # the enrolment response. If it were set from a customer's name or a
    # message, this would fail.
    window = source[source.index("dangerouslySetInnerHTML") - 200 : source.index("dangerouslySetInnerHTML") + 200]

    assert "qrSvg" in window, "the sink no longer renders qrSvg"

    setters = re.findall(r"setQrSvg\(([^)]*)\)", source)

    assert setters, "qrSvg has no setter, so its source cannot be checked"

    for setter in setters:
        assert "qr_svg" in setter or '""' in setter, (
            "qrSvg is set from something other than the server's qr_svg field "
            f"or the empty default: {setter!r}"
        )


def test_the_qr_is_generated_from_the_uri_not_from_user_markup():
    """The server side of the same guarantee: the SVG is drawn by segno from
    the otpauth URI, which becomes QR modules, not rendered text. No branch of
    it interpolates a name or a label into markup."""
    source = (ROOT / "backend/services/totp_service.py").read_text()

    assert "segno.make(uri" in source, (
        "the QR is no longer generated by segno from the URI; if it now builds "
        "SVG by hand, a label interpolated into it is an injection point"
    )
